### ISSUE TITLE
Add links to 1hive in readme

### ISSUE THREAD

**Issue by mzargham** [BlockScience/Aragon_Conviction_Voting#12]
* Link to 1hive.org with short description of the live DAO and Honey, and comments on the collaboration
* Link to the 1hive github repo containing the contracts and UIs.

**Comment by Jeff-Emmett** [comment]
https://github.com/BlockScience/Aragon_Conviction_Voting/commit/3dd0e0fcf98b019c57613575ca164075bdfbe731
