### ISSUE TITLE
Consider referencing Randomshinichi's work for the Commons Simulator 

### ISSUE THREAD

**Issue by GriffGreen** [BlockScience/Aragon_Conviction_Voting#4]
https://github.com/commons-stack/coodcad/tree/bigrewrite

Very readable!!! Object Oriented!

**Comment by mzargham** [comment]
I added @Jeff-Emmett to this issue. I think it makes sense to link it from the readme.

**Comment by aclarkData** [comment]
@mzargham @Jeff-Emmett I looked at this code when Griff suggested and is not usable for this simulation. If you want to reference that works, but the code is different from our standards and different than the 1hive implementation

**Comment by Jeff-Emmett** [comment]
https://github.com/BlockScience/Aragon_Conviction_Voting/commit/4610031e5ca0ca4f9b0ee8167ff0b628410a0580
