### ISSUE TITLE
Refactor to run in cadCAD 0.4.18

### ISSUE THREAD

**Issue by mzargham** [BlockScience/Aragon_Conviction_Voting#8]
0.4.18 introduced a configuration class which is was a breaking change with respect to this model given how we pull out the configuration objects for inspection. however it necessitates relatively minor changes to the notebook. i'd like to update v1,v2 (including workshop version), and v3 to run in 0.4.18 if possible. Or if its a more involved update, make sure v3 runs in 0.4.18 and that the local director readmes for earlier models specify which version they use (0.4.17)

**Comment by mzargham** [comment]
i tagged in @tylerdmace for support since he's already been looking at the 0.4.17 --> 0.4.18 change. Hoping you will tell us this is easy.

**Comment by aclarkData** [comment]
I thought I had all of these running in 0.4.18. I ran them all yesterday. The main difference was changing to 

from cadCAD.configuration import Experiment from appended_configs

**Comment by tylerdmace** [comment]
I'll double check them all today. I thought you had fixed them, too. Using
the new class should be the only change needed I believe, but again, I'll
verify here today.

**Comment by aclarkData** [comment]
I just reran v3 - https://github.com/BlockScience/Aragon_Conviction_Voting/blob/master/models/v3/Aragon_Conviction_Voting_Model.ipynb - with no issues. I wonder if Z's machine isn't updated to 0.4.18, or has two versions, and juptyer imported 0.4.17 instead of 0.4.18

**Comment by tylerdmace** [comment]
Yeah, running the old version after the changes have been made to update
the notebook for 0.4.18 would cause similar errors, too. That seems likely
to have happened here.

**Comment by aclarkData** [comment]
I just reran both v1 and v2 as well in the master, all good. v2_assignment doesn't run because Z had pulled some code out for the workshop. @tylerdmace :+1:
