### ISSUE TITLE
trigger function explainer notebook

### ISSUE THREAD

**Issue by mzargham** [BlockScience/Aragon_Conviction_Voting#9]
migrate material on trigger function from main simulation to its own explainer notebook. this notebook should briefly review each of the parameters, as well as the relationship to alpha (defined in its own explainer). heatmaps are provided. explain the concept of a barrier function. talk about the difference between the $\beta$ "hard limit" on share of funds dispersed, as opposed to practical limitations -- what maximum support is possible when the full token supply is placed in support of proposal. also describe the movement from "supply" to effective supply.

**Comment by aclarkData** [comment]
I copied over the initial plots  https://github.com/BlockScience/Aragon_Conviction_Voting/blob/master/models/v3/Trigger_Function_Explanation.ipynb
